# Generated by Django 3.2.9 on 2022-02-02 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20211116_1338'),
        ('terms', '0002_alter_terms_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='terms',
            unique_together={('school', 'closing_date'), ('school', 'opening_date')},
        ),
    ]
