# Generated by Django 3.1.3 on 2021-10-30 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_school_id', models.CharField(max_length=10)),
                ('tsc_number', models.CharField(max_length=15)),
                ('other_role', models.CharField(max_length=50)),
                ('subject_1', models.CharField(max_length=20)),
                ('subject_2', models.CharField(max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
                ('user', models.ForeignKey(limit_choices_to={'user_class': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacherInfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
