# Generated by Django 3.1.3 on 2021-11-01 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='activation_code',
            field=models.CharField(default='9876556', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teachers',
            name='user',
            field=models.ForeignKey(limit_choices_to={'user_class': 'Teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherInfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
