# Generated by Django 3.1.3 on 2021-11-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20211101_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='user',
        ),
    ]
