# Generated by Django 3.1.3 on 2021-11-02 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0004_teachers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='user',
            field=models.ForeignKey(limit_choices_to={'user_class': 'Teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
