# Generated by Django 3.1.3 on 2021-11-03 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_creation_date'),
        ('teachers', '0005_auto_20211102_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='school.school'),
        ),
    ]
