# Generated by Django 3.2.9 on 2022-01-26 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0006_auto_20211103_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='user',
            field=models.ForeignKey(limit_choices_to={'user_class': 'Principal'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
