# Generated by Django 3.2.9 on 2022-02-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_alter_teachers_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name_plural': 'Teachers'},
        ),
    ]
