# Generated by Django 3.2.9 on 2022-07-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_alter_teachers_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='teacher_school_id',
        ),
    ]
