# Generated by Django 3.2.9 on 2022-02-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='agriculture_pp3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='arabic_pp3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='art_design_pp3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='aviation_pp3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='electricity_pp3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='french_pp3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='german_pp3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='music_pp3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='power_mechanics_pp3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='wood_work_pp3',
            field=models.IntegerField(default=0),
        ),
    ]
