# Generated by Django 3.2.9 on 2022-02-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_auto_20220219_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='aviation_pp3',
            new_name='Aviation_pp3',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='music_pp1',
            new_name='Music_pp1',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='music_pp2',
            new_name='Music_pp2',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='music_pp3',
            new_name='Music_pp3',
        ),
    ]
