# Generated by Django 3.2.9 on 2022-02-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0004_auto_20220219_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='eng_pp1',
        ),
        migrations.AddField(
            model_name='marks',
            name='Eng_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Agri_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Agri_pp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Agri_pp3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Arabic_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Arabic_pp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Arabic_pp3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='ArtDes_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='ArtDes_pp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='ArtDes_pp3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Aviation_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Aviation_pp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Aviation_pp3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='BST_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='BST_pp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Bio_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Bio_pp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Bio_pp3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='CST_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='CST_pp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Chem_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Chem_pp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Chem_pp3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Electricity_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Electricity_pp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Electricity_pp3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Eng_pp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Eng_pp3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Fre_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Fre_pp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Fre_pp3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Geo_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Geo_pp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Ger_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Ger_pp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Ger_pp3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='HSC_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='HSC_pp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='HSC_pp3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Hist_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Hist_pp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Kis_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Kis_pp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Kis_pp3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Mat_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Mat_pp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Music_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Music_pp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Music_pp3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Phy_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Phy_pp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Phy_pp3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='PowMec_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='PowMec_pp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='PowMec_pp3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='RE_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='RE_pp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='WW_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='WW_pp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='WW_pp3',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
