# Generated by Django 3.2.9 on 2022-04-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0005_auto_20220219_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='Building_Construction_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='Building_Construction_pp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='Building_Construction_pp3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='Kenya_Sign_Language_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='Kenya_Sign_Language_pp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='Kenya_Sign_Language_pp3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='Metal_Work_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='Metal_Work_pp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='Metal_Work_pp3',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
