# Generated by Django 3.2.9 on 2022-04-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0006_auto_20220419_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='Metal_Work_pp2',
            new_name='MW_pp1',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='Metal_Work_pp1',
            new_name='MW_pp2',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='Metal_Work_pp3',
            new_name='MW_pp3',
        ),
    ]
