# Generated by Django 3.2.9 on 2022-04-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0007_auto_20220419_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='Building_Construction_pp1',
            new_name='BC_pp1',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='Building_Construction_pp2',
            new_name='BC_pp2',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='Building_Construction_pp3',
            new_name='BC_pp3',
        ),
    ]
