# Generated by Django 3.2.9 on 2022-04-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0008_auto_20220419_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='Kenya_Sign_Language_pp2',
            new_name='KSL_pp2',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='Kenya_Sign_Language_pp1',
            new_name='KSL_pp3',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='Kenya_Sign_Language_pp3',
        ),
        migrations.AddField(
            model_name='marks',
            name='KSL_pp1',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
