# Generated by Django 3.2.9 on 2022-04-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0010_auto_20220419_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='Kenya_Sign_Language_pp1',
            new_name='KSL_pp1',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='Kenya_Sign_Language_pp2',
            new_name='KSL_pp2',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='Kenya_Sign_Language_pp3',
            new_name='KSL_pp3',
        ),
    ]
