# Generated by Django 3.2.9 on 2022-04-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0011_auto_20220419_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='Agri_pp1',
            field=models.IntegerField(default=62, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Agri_pp2',
            field=models.IntegerField(default=62, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Agri_pp3',
            field=models.IntegerField(default=62, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='BST_pp1',
            field=models.IntegerField(default=67, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='BST_pp2',
            field=models.IntegerField(default=67, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Bio_pp1',
            field=models.IntegerField(default=60, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Bio_pp2',
            field=models.IntegerField(default=60, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Bio_pp3',
            field=models.IntegerField(default=30, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Chem_pp1',
            field=models.IntegerField(default=60, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Chem_pp2',
            field=models.IntegerField(default=60, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Chem_pp3',
            field=models.IntegerField(default=30, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Eng_pp1',
            field=models.IntegerField(default=50, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Eng_pp2',
            field=models.IntegerField(default=50, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Eng_pp3',
            field=models.IntegerField(default=50, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Geo_pp1',
            field=models.IntegerField(default=67, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Geo_pp2',
            field=models.IntegerField(default=67, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Ger_pp1',
            field=models.IntegerField(default=62, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Ger_pp2',
            field=models.IntegerField(default=62, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Ger_pp3',
            field=models.IntegerField(default=62, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='HSC_pp1',
            field=models.IntegerField(default=62, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='HSC_pp2',
            field=models.IntegerField(default=62, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='HSC_pp3',
            field=models.IntegerField(default=62, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Hist_pp1',
            field=models.IntegerField(default=67, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Hist_pp2',
            field=models.IntegerField(default=67, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='KSL_pp1',
            field=models.IntegerField(default=62, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='KSL_pp2',
            field=models.IntegerField(default=62, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='KSL_pp3',
            field=models.IntegerField(default=62, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Kis_pp1',
            field=models.IntegerField(default=50, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Kis_pp2',
            field=models.IntegerField(default=50, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Kis_pp3',
            field=models.IntegerField(default=50, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Mat_pp1',
            field=models.IntegerField(default=56, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Mat_pp2',
            field=models.IntegerField(default=56, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Phy_pp1',
            field=models.IntegerField(default=60, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Phy_pp2',
            field=models.IntegerField(default=60, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Phy_pp3',
            field=models.IntegerField(default=30, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='RE_pp1',
            field=models.IntegerField(default=67, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='RE_pp2',
            field=models.IntegerField(default=67, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
