# Generated by Django 3.2.9 on 2022-05-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0015_marks_cst_pp3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='Agri_pp3',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='CST_pp3',
        ),
    ]
