# Generated by Django 3.2.9 on 2021-12-09 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0003_auto_20211116_1338'),
        ('stream', '0003_auto_20211107_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.IntegerField()),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('kcpe_marks', models.IntegerField()),
                ('admission_date', models.DateField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stream.streams')),
            ],
        ),
    ]
