# Generated by Django 3.2.9 on 2021-12-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_students_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='activation_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
