# Generated by Django 3.2.9 on 2022-05-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_students_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='subject_1',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='subject_2',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='subject_3',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='subject_4',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='subject_5',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='subject_6',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='subject_7',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='subject_8',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='subject_9',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
