# Generated by Django 3.2.9 on 2022-05-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20220522_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='subject_1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='subject_2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='subject_3',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='subject_4',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='subject_5',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='subject_6',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='subject_7',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='subject_8',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='subject_9',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
