# Generated by Django 3.2.9 on 2022-05-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20220522_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='admission_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
