# Generated by Django 3.2.9 on 2022-05-23 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_students_admission_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='subject_6',
        ),
        migrations.RemoveField(
            model_name='students',
            name='subject_7',
        ),
        migrations.RemoveField(
            model_name='students',
            name='subject_8',
        ),
        migrations.RemoveField(
            model_name='students',
            name='subject_9',
        ),
    ]
