# Generated by Django 3.2.9 on 2022-06-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20220523_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.AlterUniqueTogether(
            name='students',
            unique_together={('first_name', 'last_name')},
        ),
    ]
