# Generated by Django 3.2.9 on 2022-06-17 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_rename_mpesa_till_number_school_mpesa_business_number'),
        ('students', '0012_auto_20220617_1029'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='students',
            unique_together={('first_name', 'last_name', 'school')},
        ),
    ]
