# Generated by Django 3.1.3 on 2021-10-30 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import school.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50, null=True)),
                ('school_code', models.CharField(max_length=20, null=True)),
                ('school_telephone', models.CharField(max_length=20, null=True)),
                ('school_email', models.CharField(max_length=50, null=True)),
                ('postal_address', models.CharField(max_length=20, null=True)),
                ('postal_code', models.CharField(max_length=20, null=True)),
                ('town', models.CharField(max_length=20, null=True)),
                ('vision', models.CharField(max_length=200, null=True)),
                ('mission', models.CharField(max_length=200, null=True)),
                ('motto', models.CharField(max_length=200, null=True)),
                ('logo', models.FileField(null=True, upload_to='school_logos')),
                ('county', models.CharField(max_length=50, null=True)),
                ('sub_county', models.CharField(max_length=50, null=True)),
                ('mpesa_business_number', models.CharField(max_length=20, null=True)),
                ('mpesa_account_number', models.CharField(max_length=20, null=True)),
                ('bank_name', models.CharField(max_length=100, null=True)),
                ('bank_account_number', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('activation_code', models.CharField(default=school.models.activation_code_generator, max_length=12)),
            ],
            options={
                'verbose_name_plural': 'Schools',
            },
        ),
        migrations.CreateModel(
            name='principal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.OneToOneField(limit_choices_to={'user_class': 'Principal'}, on_delete=django.db.models.deletion.CASCADE, related_name='principal', to=settings.AUTH_USER_MODEL)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='school.school')),
            ],
            options={
                'verbose_name_plural': 'Principals',
            },
        ),
    ]
