# Generated by Django 3.1.3 on 2021-11-16 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0002_school_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='principal',
            field=models.OneToOneField(limit_choices_to={'user_class': 'Principal'}, on_delete=django.db.models.deletion.PROTECT, related_name='principal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='principal',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='school', to='school.school'),
        ),
    ]
