# Generated by Django 3.2.9 on 2022-02-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20211116_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.FileField(null=True, upload_to='media/school_logos'),
        ),
    ]
