# Generated by Django 3.2.9 on 2022-02-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_school_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.FileField(null=True, upload_to='school_logos'),
        ),
    ]
