# Generated by Django 3.2.9 on 2022-06-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20220616_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='mpesa_till_number',
            new_name='mpesa_business_number',
        ),
    ]
