# Generated by Django 3.2.9 on 2022-07-24 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_rename_mpesa_till_number_school_mpesa_business_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='school',
            name='mpesa_account_number',
        ),
        migrations.RemoveField(
            model_name='school',
            name='mpesa_business_number',
        ),
    ]
