# Generated by Django 3.2.9 on 2022-07-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20220724_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='bank_account_number',
            field=models.CharField(default=174379, max_length=100, null=True),
        ),
    ]
