# Generated by Django 3.2.9 on 2022-04-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_auto_20220418_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electives',
            name='elective',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
