# Generated by Django 3.2.9 on 2022-05-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_students_parent'),
        ('subjects', '0007_subhjectstudent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubhjectStudent',
            new_name='SubjectStudent',
        ),
    ]
