# Generated by Django 3.2.9 on 2022-05-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_rename_subhjectstudent_subjectstudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectStudent',
        ),
    ]
