# Generated by Django 3.2.9 on 2022-01-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='title',
            field=models.CharField(default='Form 3 Academic Day', max_length=200),
        ),
    ]
