# Generated by Django 3.2.9 on 2022-01-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_events_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='target_audience',
            field=models.CharField(choices=[('All', 'All'), ('Teachers', 'Teachers'), ('Parents', 'Parents')], default='All', max_length=30),
        ),
    ]
