# Generated by Django 3.1.3 on 2021-11-07 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_auto_20211103_1506'),
        ('stream', '0002_auto_20211107_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streams',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teachers'),
        ),
    ]
