# Generated by Django 3.2.9 on 2022-01-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_auto_20211107_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='streams',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
