# Generated by Django 3.2.9 on 2022-01-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0008_alter_streams_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streams',
            name='stream_name',
            field=models.CharField(max_length=45),
        ),
    ]
