# Generated by Django 3.2.9 on 2022-04-21 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_school_logo'),
        ('teachers', '0009_alter_teachers_options'),
        ('stream', '0009_alter_streams_stream_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='stream_subject_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream.streams')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teachers')),
            ],
            options={
                'verbose_name_plural': 'stream subject teachers',
            },
        ),
    ]
