# Generated by Django 3.2.9 on 2022-04-21 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_alter_teachers_options'),
        ('school', '0005_alter_school_logo'),
        ('stream', '0011_alter_stream_subject_teacher_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stream_subject_teacher',
            unique_together={('school', 'stream', 'subject'), ('school', 'stream', 'teacher', 'subject')},
        ),
    ]
