# Generated by Django 3.2.9 on 2022-06-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='target_audience',
            field=models.CharField(choices=[('All', 'All'), ('Teachers', 'Teachers'), ('Parents', 'Parents'), ('SUb staff', 'Sub staff')], max_length=15),
        ),
    ]
