# Generated by Django 3.1.3 on 2021-10-30 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('teachers', '0001_initial'),
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.IntegerField()),
                ('subject', models.CharField(max_length=20)),
                ('day', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream.streams')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachers.teachers')),
            ],
        ),
    ]
