# Generated by Django 3.2.9 on 2021-11-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20211118_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='form',
            field=models.IntegerField(null=True),
        ),
    ]
