# Generated by Django 3.2.9 on 2022-01-09 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_auto_20211103_1506'),
        ('timetable', '0003_timetable_form'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('lesson_number', 'teacher', 'day')},
        ),
    ]
