# Generated by Django 3.2.9 on 2022-03-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_alter_teachers_options'),
        ('stream', '0009_alter_streams_stream_name'),
        ('timetable', '0005_alter_timetable_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('lesson_number', 'teacher', 'day', 'stream')},
        ),
    ]
