# Generated by Django 3.2.9 on 2022-04-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0009_alter_streams_stream_name'),
        ('timetable', '0006_alter_timetable_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('lesson_number', 'day', 'stream')},
        ),
    ]
