# Generated by Django 3.2.9 on 2022-04-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_alter_timetable_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='teacher',
        ),
    ]
