# Generated by Django 3.2.9 on 2022-04-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_remove_timetable_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='subject',
            field=models.CharField(max_length=60),
        ),
    ]
