# Generated by Django 3.2.9 on 2022-05-31 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_school_logo'),
        ('stream', '0012_alter_stream_subject_teacher_unique_together'),
        ('timetable', '0010_alter_timetable_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('school', 'stream', 'form', 'lesson_number', 'day')},
        ),
    ]
