# Generated by Django 3.2.9 on 2022-06-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_alter_timetable_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
    ]
