# Generated by Django 3.2.9 on 2022-06-29 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_alter_timetable_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='form',
        ),
    ]
