# Generated by Django 3.2.9 on 2022-06-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subStaff', '0002_alter_substaff_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='substaff',
            old_name='activation',
            new_name='activation_code',
        ),
    ]
