# Generated by Django 3.2.9 on 2022-06-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subStaff', '0003_rename_activation_substaff_activation_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='substaff',
            old_name='sub_staff_name',
            new_name='role',
        ),
    ]
