# Generated by Django 3.2.9 on 2022-06-12 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_school_logo'),
        ('subStaff', '0004_rename_sub_staff_name_substaff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substaff',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_staff', to='school.school'),
        ),
    ]
