# Generated by Django 3.2.9 on 2022-06-12 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_school_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subStaff', '0005_alter_substaff_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substaff',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
        migrations.AlterField(
            model_name='substaff',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
