# Generated by Django 3.2.9 on 2022-07-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subStaff', '0006_auto_20220612_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='substaff',
            name='date',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
