# Generated by Django 3.2.9 on 2022-07-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subStaff', '0007_substaff_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substaff',
            name='date',
        ),
        migrations.AddField(
            model_name='substaff',
            name='date_created',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
