# Generated by Django 3.2.9 on 2022-02-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20211116_1338'),
        ('permisions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'verbose_name_plural': 'Permissions'},
        ),
        migrations.AlterUniqueTogether(
            name='permissions',
            unique_together={('school', 'userType')},
        ),
    ]
