# Generated by Django 3.2.9 on 2022-02-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisions', '0002_auto_20220205_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='userType',
            field=models.CharField(choices=[('Deputy principal academics', 'Deputy principal academics'), ('Deputy principal administration', 'Deputy principal administration'), ('DoS', 'DoS'), ('Senior teacher', 'Senior teacher'), ('Class teacher', 'Class teacher')], max_length=50),
        ),
    ]
