# Generated by Django 3.2.9 on 2022-06-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisions', '0004_alter_permissions_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='create_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissions',
            name='read_suggestion_box',
            field=models.BooleanField(default=False),
        ),
    ]
