# Generated by Django 3.2.9 on 2022-05-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20220504_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesheet',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
