# Generated by Django 3.2.9 on 2022-05-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_students_status'),
        ('attendance', '0004_alter_attendancesheet_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancesheet',
            unique_together={('student', 'date')},
        ),
    ]
