# Generated by Django 3.2.9 on 2022-05-09 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_students_status'),
        ('fee', '0002_alter_feestructure_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('amount', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
        ),
    ]
