# Generated by Django 3.2.9 on 2022-05-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0004_feestatement_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestatement',
            name='ref_code',
            field=models.CharField(max_length=20),
        ),
    ]
