# Generated by Django 3.2.9 on 2022-05-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_students_status'),
        ('fee', '0005_alter_feestatement_ref_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feestatement',
            unique_together={('student', 'ref_code', 'description', 'amount', 'balance', 'date')},
        ),
    ]
