# Generated by Django 3.2.9 on 2022-07-22 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0008_mpesacallbacks_mpesacalls_mpesapayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpesacalls',
            old_name='caller',
            new_name='CheckoutRequestID',
        ),
        migrations.RenameField(
            model_name='mpesacalls',
            old_name='content',
            new_name='ResponseDescription',
        ),
        migrations.RemoveField(
            model_name='mpesacalls',
            name='conversation_id',
        ),
        migrations.RemoveField(
            model_name='mpesacalls',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='organization_balance',
        ),
    ]
