# Generated by Django 3.2.9 on 2022-07-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0009_auto_20220722_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesapayment',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='type',
        ),
    ]
