# Generated by Django 3.2.9 on 2022-07-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0010_auto_20220723_0927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MpesaCallBacks',
        ),
        migrations.RemoveField(
            model_name='mpesacalls',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mpesacalls',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='updated_at',
        ),
    ]
