# Generated by Django 3.1.3 on 2021-10-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50, verbose_name='FirstName')),
                ('last_name', models.CharField(max_length=50, verbose_name='LastName')),
                ('email_address', models.EmailField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('national_id', models.CharField(max_length=8)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('user_class', models.CharField(choices=[('Principal', 'Principal'), ('Teacher', 'Teacher'), ('Parent', 'Parent')], max_length=50)),
                ('profile_photo', models.FileField(null=True, upload_to='profile_photos')),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='Date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
    ]
