# Generated by Django 3.2.9 on 2022-06-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_class',
            field=models.CharField(choices=[('Principal', 'Principal'), ('Teacher', 'Teacher'), ('Parent', 'Parent'), ('Sub staff', 'Sub staff')], max_length=50),
        ),
    ]
